### ISSUE TITLE
FTP broke

### ISSUE THREAD

**Issue by leebaird** [L1ghtn1ng/Egress-Assess#2]
Kali 1
./Egress-Assess.py --server ftp --username lee --password hack

Kali 2
./Egress-Assess.py --client ftp --username lee --password hack --ip 192.168.1.5 --file /tmp/secret.txt

Kali 1
```
[I 2020-11-17 19:24:40] concurrency model: async
[I 2020-11-17 19:24:40] masquerade (NAT) address: None
[I 2020-11-17 19:24:40] passive ports: 60000->60099
[I 2020-11-17 19:24:40] >>> starting FTP server on 0.0.0.0:21, pid=1713 <<<
[I 2020-11-17 19:25:04] 192.168.1.10:46527-[] FTP session opened (connect)
[I 2020-11-17 19:25:04] 192.168.1.10:46527-[lee] USER 'lee' logged in.
[I 2020-11-17 19:25:34] 192.168.1.10:46527-[lee] Passive data channel timed out.
[I 2020-11-17 19:25:52] 192.168.1.10:46527-[lee] FTP session closed (disconnect).
```

Kali 2
Nothing

**Comment by L1ghtn1ng** [comment]
This has been fixed

**Comment by L1ghtn1ng** [comment]
turns out it was simple to fix in the end which was so darn hard to fix but managed to get my google foo correct this time https://github.com/L1ghtn1ng/Egress-Assess/commit/639dfea3d5811e99b638c1f6213439816848de62
