### ISSUE TITLE
HTTPS broke

### ISSUE THREAD

**Issue by leebaird** [L1ghtn1ng/Egress-Assess#5]
Kali 1
./Egress-Assess.py --server https

```
[*] Starting web (https) server...
[*] Web server is currently running
[*] Type "kill -9 " 923 + "" to stop the web server.
[*][*] Error: Port 443 is currently in use!
[*][*] Error: Please restart when port is free!
```

kill -9 923
`-bash: kill: (923) - No such process`

NOTE: apache2 was not running. Verified with netstat.

**Comment by L1ghtn1ng** [comment]
HTTPS is not broke and that is an old version from looking at that output try using ```sudo ./Egress-Assess.py --server https```  I cannot replicate your issue so I think it is something specific to your environment and without access to it I cannot have a look to see what is going on
