### ISSUE TITLE
SMB broke

### ISSUE THREAD

**Issue by leebaird** [L1ghtn1ng/Egress-Assess#6]
Kali 1
./Egress-Assess.py --server smb

Kali 2
./Egress-Assess.py --client smb --ip <IP> --file /tmp/secret.txt

```
smbclient \\\\192.168.1.5\\DATA -N -c "put /tmp/secret.txt secret.txt"
do_connect: Connection to 192.168.1.5 failed (Error NT_STATUS_IO_TIMEOUT)
[*] File Transmitted! 
```

NOTE: file was not transmitted.

**Comment by L1ghtn1ng** [comment]
fixed with commit 6da51bf

**Comment by leebaird** [comment]
Still broke.

**Comment by leebaird** [comment]
Problem was related to ISP blocking port 445.
