### ISSUE TITLE
Quit HTTP server nicely

### ISSUE THREAD

**Issue by leebaird** [L1ghtn1ng/Egress-Assess#8]
[snip]

[+] 2020-10-22 00:41:03 - Received File - secrets.txt

NOTE: I used ctrl + c to stop the server. 
Try to stop the http server nicely so that the user doesn't see the following:

```
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

**Comment by L1ghtn1ng** [comment]
From me having a look at this I have absolutely no idea how to fix this, the things that normally work dont and as this is a nice to have am going to close it
